plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\savir\\Projects\\receipt-scanner\\.claude\\worktrees\\relaxed-dubinsky-6758df\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\savir\\Projects\\receipt-scanner\\.claude\\worktrees\\relaxed-dubinsky-6758df"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]